package com.roomandlivedataroom1.Utils;

import com.roomandlivedataroom1.Models.NoteEntity;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

public class SampleDataProvider {
    private static final String SAMPLE_TEXT_1 = "A simple note";
    private static final String SAMPLE_TEXT_2 = "A note with a\nline feed";
    private static final String SAMPLE_TEXT_3 = "The Battle of Nicopolis took place on 25 September 1396 and resulted in the rout of an allied crusader army of Hungarian, Croatian, Bulgarian, Wallachian, French, Burgundian, German, and assorted troops (assisted by the Venetian navy) at the hands of an Ottoman force, raising the siege of the Danubian fortress of Nicopolis and leading to the end of the Second Bulgarian Empire. It is often referred to as the Crusade of Nicopolis as it was one of the last large-scale Crusades of the Middle Ages, together with the Crusade of Varna in 1443–1444." +
            "There were many minor crusades in the 14th century, undertaken by individual kings or knights. Most recently there had been a failed crusade against Tunisia in 1390, and there was ongoing warfare in northern Europe along the Baltic coast. After the Battle of Kosovo in 1389, the Ottomans had conquered most of the Balkans and had reduced the Byzantine Empire to the area immediately surrounding Constantinople, which they blockaded from 1394 on.[citation needed]\n" +
            "\n" +
            "In 1393 the Bulgarian tsar Ivan Shishman had lost Nicopolis — his temporary capital — to the Ottomans, while his brother, Ivan Stratsimir, still held Vidin but had been reduced to an Ottoman vassal. In the eyes of the Bulgarian boyars, despots, and other independent Balkan rulers, the crusade was a great chance to reverse the course of the Ottoman conquest and take back the Balkans from Islamic rule. In addition, the front line between Islam and Christianity had been moving slowly towards the Kingdom of Hungary. The Kingdom of Hungary was now the frontier between the two religions in Eastern Europe, and the Hungarians were in danger of being attacked themselves. The Republic of Venice feared that Ottoman control of the Balkan peninsula, which included Venetian territories like parts of Morea and Dalmatia, would reduce their influence over the Adriatic Sea, Ionian Sea, and Aegean Sea. The Republic of Genoa, on the other hand, feared that if the Ottomans were to gain control over River Danube and the Turkish Straits, they would eventually obtain a monopoly over the trade routes between Europe and the Black Sea, where the Genoese had many important colonies like Caffa, Sinop, and Amasra. The Genoese also owned the citadel of Galata, located at the north of the Golden Horn in Constantinople, to which Bayezid had laid siege in 1395.[citation needed]\n" +
            "\n" +
            "In 1394, Pope Boniface IX proclaimed a new crusade against the Turks, although the Western Schism had split the papacy in two, with rival popes at Avignon and Rome, and the days when a pope had the authority to call a crusade were long past.[citation needed]\n" +
            "\n" +
            "The two decisive factors in the formation of the last crusade were the ongoing Hundred Years' War between Richard II's England and Charles VI's France and the support of Philip II, Duke of Burgundy.[10] In 1389, the war had ground to one of its periodic truces. Further, in March 1395, Richard II proposed a marriage between himself and Charles VI's daughter Isabella in the interests of peace and the two kings met in October 1396 on the borders of Calais to agree to the union and agree to lengthen the Truce of Leulinghem.[11] The support of Burgundy, among the most powerful of the French nobles, was also vital. In 1391, Burgundy, trying to decide between sending a crusade to either Prussia or Hungary, sent his envoy Guy de La Trémoille to Venice and Hungary to evaluate the situation. Burgundy originally envisioned a crusade led by himself and the Dukes of Orléans and Lancaster, though none would join the eventual crusade. It was very unlikely that defense against the Turks was considered a particularly important goal of the crusade. Burgundy's interest in sponsoring the crusade was in increasing his and his house's prestige and power and, historian Barbara Tuchman notes, \"since he was the prince of self-magnification, the result was that opulent display became the dominant theme; plans, logistics, intelligence about the enemy came second, if at all.\"[12] In 1394, Burgundy extracted 120,000 livres from Flanders, sufficient to begin preparations for a crusade, and in January 1395 sent word to King Sigismund of Hungary that an official request to the King of France would be accepted.[12]\n" +
            "\n" +
            "In August, Sigismund's delegation of four knights and a bishop arrived in the court of Paris to paint a description of how \"40,000\" Turks were despoiling and imperiling Christian lands and beg, on Sigismund of Hungary's behalf, for help. Charles VI, having secured a peace with England through the marriage of his daughter, was able to reply that it was his responsibility to protect Christianity and punish Sultan Bayezid. French nobility responded enthusiastically to the declaration; Philip of Artois, Count of Eu, the Constable of France, and Jean Le Maingre, the Marshal of France, declared participation in the crusade the duty of every \"man of valor\".[13]" +
            "The number of combatants is heavily contested in historical accounts. Historian Tuchman notes, \"Chroniclers habitually matched numbers to the awesomeness of the event,\" and the Battle of Nicopolis was considered so significant that the number of combatants given by medieval chroniclers ranges as high as 400,000, with each side insisting that the enemy outnumbered them two-to-one, which for the crusaders offered some solace for their defeat and for the Turks increased the glory of their victory. The oft-given figure of 100,000 crusaders is dismissed by Tuchman, who notes that 100,000 men would have taken a month to cross the Danube at Iron Gate, while the crusaders took eight days.[14]\n" +
            "\n" +
            "The closest record to a first-person account was made by Johann Schiltberger, a German follower of a Bavarian noble, who witnessed the battle at the age of 16 and was captured and enslaved for 30 years by the Turks before returning home, at which time he wrote a narrative of the battle estimating the crusader strength at the final battle at 17,000,[14] though he also overestimated Turkish forces as a wildly inflated 200,000.[15] German historians of the 19th century attempting to estimate the combatants on each side came to the figures of about 7,500–15,000 Christians and about 12,000–20,000 Turks, while noting that, from the point of logistics, it would have been impossible for the countryside around Nicopolis to have supplied food and fodder for scores of thousands of men and horses.[14] (Medieval armies acquired supplies by taking them from the surrounding area as they marched, as opposed to using the supply lines of modern armies.)" +
            "From France, it was said about 5,000 knights and squires joined, and were accompanied by 6,000 archers and foot soldiers drawn from the best volunteer and mercenary companies; totalling some 11,000 men.[18] Next in importance were the Knights Hospitaller of Rhodes, who were the standard bearers of Christianity in the Levant since the decline of Constantinople and Cyprus. Venice supplied a naval fleet for supporting action, while Hungarian envoys encouraged German princes of the Rhineland, Bavaria, Saxony, and other parts of the empire to join. French heralds had proclaimed the crusade in Poland, Bohemia, Navarre, and Spain, from which individuals came to join.[2]\n" +
            "\n" +
            "The Italian city-states were too much engaged in their customary violent rivalries to participate, and the widely reported and acclaimed English participation never actually occurred. The report of 3,000 English knights comes from contemporary Antonio Fiorentino, and was taken as fact by historian Aziz S. Atiya and others following him. A thousand knights would have actually amounted to \"four to six thousand men and at least twice as many horses\", counting foot-soldiers and other retainers. However, there are no records of financial arrangements being made in England to send a force abroad, nor of any royal preparation needed to organize and dispatch such a force. Reports of Henry of Bolingbroke or other \"son of the Duke of Lancaster\" leading an English contingent must be false since the presence of Henry and every other such son, as well as almost every other significant noble in the land, is recorded at the King's wedding five months after the crusade's departure. Atiya also thought that the invocation of St. George as a war cry at Nicopolis signified the presence of English soldiers, for whom George was a patron saint; but Froissart, who mentions this, claims that the cry was made by the French knight Philippe d'Eu. Furthermore, there was no collection of ransom money in England to pay for captives, as there was in every other country that had sent men to the battle. Sporadic mention in contemporary accounts of the presence of \"English\" may be attributed to Knights Hospitaller of the English langue subgrouping, who joined their comrades for the crusade after leaving Rhodes (where the Hospitallers were based at the time) and sailing up the Danube.[19] Possible reasons for the English absence include the increasing tension between the King and the Duke of Gloucester, which may have convinced the two that they had best keep their supporters close, and the antipathy caused by the long war between the English and French, resulting in the English refusing to consider putting themselves under a French-led crusade, regardless of the recently concluded peace.[2]\n" +
            "\n" +
            "Nevertheless, obviously inflated figures continue to be repeated. These include 6,000–12,000 Hungarians,[20][page needed][21][page needed] ≈11,000 French, English and Burgundian[21][page needed] troops, ≈12,000 Wallachians led by Mircea cel Batran (Mircea the Elder) the Prince of Wallachia,[22] ≈6,000 Germans[22] and nearly 15,000[22] Dutch, Bohemian, Spanish, Italian, Polish, Bulgarian, Scottish and Swiss troops on the land, with the naval support of Venice, Genoa and the Knights of St. John. These result in a figure of about 47,000 – 49,000 in total; possibly up to 120,000 or 130,000 according to numerous sources, including the Ottoman historian Şükrullah who, in the 1460s, gives the figure of the crusader army as 130,000 in his Behçetu't-Tevârih.[16][23]\n" +
            "\n" +
            "Composition of Ottoman forces\n" +
            "The strength of the Ottoman forces is also estimated at about 15–20,000;[20] but inflated figures are common here as well. Numerous sources provide estimates of the size of the army as up to 60,000 including the Ottoman historian Şükrullah, who, writing in the 1460s, gives the figure of the Ottoman army as 60,000 in his Behçetu't-Tevârih;[16] alternately described as roughly half of the Crusader army.[23] The Ottoman force also included 1,500 Serbian heavy cavalry knights[24] under the command of Prince Stefan Lazarević, who was Sultan Bayezid's brother-in-law and vassal since the Battle of Kosovo in 1389.[1]";


    private static Date getDate(int diffAmount){
        GregorianCalendar calendar=new GregorianCalendar();
        calendar.add(Calendar.MILLISECOND,diffAmount);
        return calendar.getTime();
    }

    public static List<NoteEntity> getSampleData(){

        List<NoteEntity> notesList=new ArrayList<>();

        notesList.add(new NoteEntity(getDate(0),SAMPLE_TEXT_1));
        notesList.add(new NoteEntity(getDate(-1),SAMPLE_TEXT_2));
        notesList.add(new NoteEntity(getDate(-2),SAMPLE_TEXT_3));

        return notesList;

    }
}
